import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>TIDV Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport"    content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/icon.ico" />
      </Head>
      <main>
        <h1>Hello World</h1>
      </main>
    </>
  )
}
